branches:
  except:
    - gh-pages
language: perl6
sudo: false
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda installdeps .
script:
  - perl6 -e 'say "1..1\n ok 1"'
branches:
  only:
  - master
